package fr.euphyllia.fidorial.gradle.libraries

import org.gradle.api.DefaultTask
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Classpath
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import java.util.zip.ZipFile

/**
 * Lists every package reachable from `fidorial-api` and its `api` dependencies.
 *
 * At runtime the plugin class loader treats these packages as parent-first: a plugin that
 * bundles its own Adventure or Gson still gets the server's copy, so a `Component` crossing
 * the API boundary is never a `ClassCastException`. Everything outside this list is
 * child-first, which is what lets two plugins ship conflicting versions of the same library.
 */
@CacheableTask
abstract class GenerateApiPackageIndexTask : DefaultTask() {

    @get:Classpath
    abstract val apiSurface: ConfigurableFileCollection

    @get:OutputDirectory
    abstract val outputDirectory: DirectoryProperty

    @TaskAction
    fun generate() {
        val packages = sortedSetOf<String>()

        apiSurface.files.filter { it.isFile && it.name.endsWith(".jar") }.forEach { jar ->
            ZipFile(jar).use { zip ->
                zip.entries().asSequence()
                    .filter { !it.isDirectory && it.name.endsWith(".class") }
                    .forEach { entry ->
                        val separator = entry.name.lastIndexOf('/')
                        if (separator > 0) {
                            packages += entry.name.substring(0, separator).replace('/', '.')
                        }
                    }
            }
        }

        packages.removeIf { it.startsWith("META-INF") }

        val output = outputDirectory.get().asFile.resolve("META-INF/fidorial/api-packages.list")
        output.parentFile.mkdirs()
        output.writeText(
            "# Packages owned by the server: always loaded parent-first for plugins.\n" +
                    "# Generated by the '$name' task — do not edit.\n" +
                    packages.joinToString("\n", postfix = "\n"),
        )
        logger.lifecycle("API package index: ${packages.size} packages")
    }

    companion object {
        const val API_PACKAGE_INDEX_CATEGORY = "apiPackageIndex"
    }
}
